# Disable all bungeecord commands if not yet authenticated (other than 2fa ones)
Disable Commands: true

# Disable the ability to switch servers if not yet authenticated
Disable Server Switch: true

# If the above is true you can whitelist commands with the below
Whitelisted Commands:
  - "help"

# If commands are not disabled you can use the below to blacklist specific commands instead
Blacklisted Commands:
  - "op"
  - "spawn"