enable: true

enablelegacyblacklistitems: false

enablechatfilter: true

disable-enderman-pickup: true

Essentials-Replacement: true

discord-link: REPLACE THIS WITH DISCORD LINK

#Default Database. Don't Change
Database-Username: AetheriaCorePlugin

Database-Password: AetheriaCorePlugin

#------- DEBUG OPTIONS -------#
enableDatabase: true
#DO NOT TURN THIS OFF. IT MAY BREAK THE PLUGIN. THIS IS FOR DEBUGGING ONLY.