enable: true

enablelegacyblacklistitems: false

enablechatfilter: true

disable-enderman-pickup: true

#------- DEBUG OPTIONS -------#
enableDatabase: true
#DO NOT TURN THIS OFF. IT MAY BREAK THE PLUGIN. THIS IS FOR DEBUGGING ONLY.


#Variables

togglepvp: true