Config-Version: 1.0

Server-Type: NOT-SET

enable: true

enablelegacyblacklistitems: false

enablechatfilter: true

disable-enderman-pickup: true

#NOT IN USE
#Essentials-Replacement: true

#NOT IN USE
#check-for-updates: true

#discord-link: REPLACE THIS WITH DISCORD LINK

StaffChat-Channel: aetheriacore-1 #define in DiscordSRV config

#db
Database-Username: DEFAULT-CHANGE-THIS
Database-Password: DEFAULT-CHANGE-THIS
Database-Url: DEFAULT-CHANGE-THIS
Database-Name: DEFAULT-CHANGE-THIS

Custom-DB-port: false
Database-port: 3306
#------- DEBUG OPTIONS -------#
enableDatabase: true
#DO NOT TURN THIS OFF. IT MAY BREAK THE PLUGIN. THIS IS FOR DEBUGGING ONLY.

#Plugin Version
#uses a GET request on https://badbird5907.net/api/aetheriacore/version
#change check-for-updates: true to check-for-updates: false to disable update checking
version: 2.0

#vars
pvp: true